### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by rkeane2** [matthias-k/cyipopt#46]
I should start by saying I am not a software developer. I know what dll stands for, but I don't know what it actually does, and I've never used a compiler in my life. I am an academic and want to use ipopt for research purposes. 

I cannot figure out how to install the package. This is what I've tried. From the anaconda console,

conda install -c conda-forge ipopt 

The package will install, and I can see it with 'conda list'. Inside python if I use  " help('modules') "  ipopt will not be shown. 

 Next I tried to install manually following the instructions given. I downloaded the ipopt 3.11 for winx64 from https://www.coin-or.org/download/binary/Ipopt/ and the source files for cyipopt. I looked inside setup.py, but I don't understand what is going on and so I'm not really sure what I am supposed to be changing here. I looked at the ipopt files and there is a folder 'lib' which contains several .lib files as well as another folder pkgconfig. There are no .dlls anywhere. 

I ran setup.py and it returns this 

fatal error C1083: Cannot open include file: 'IpStdCInterface.h': No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.21.27702\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

**Comment by moorepants** [comment]
If you want to download a precompiled binary of ipopt, I think this file is your best bet: https://www.coin-or.org/download/binary/Ipopt/Ipopt-3.11.0-Win32-Win64-dll.7z

You then have to get a compiler running on windows and edit the setup.py file to point to the directory of these binaries. I have not successfully gotten this to work myself, but it should be possible.

**Comment by moorepants** [comment]
It may be easier to install ubuntu on windows from the app store or via something like virtualbox and just install from conda.

**Comment by rkeane2** [comment]
I'll give it a try with the binaries you linked and report back if it works. Thanks. 

What I'm still confused about though is why 
conda install ipopt
doesn't work?

**Comment by moorepants** [comment]
There are no windows ipopt binaries built on conda forge yet, so we can't build cyipopt binaires. See: https://github.com/conda-forge/cyipopt-feedstock/issues/6

**Comment by hd1894** [comment]
> I'll give it a try with the binaries you linked and report back if it works. Thanks.
> 
> What I'm still confused about though is why
> conda install ipopt
> doesn't work?

I have the same situation and the same problem.
Did you manage to succeed?

**Comment by moorepants** [comment]
As soon as someone successfully builds this on windows in a reproducible way, we would love to have that added to the documentation. Thanks.

**Comment by hd1894** [comment]
> It may be easier to install ubuntu on windows from the app store or via something like virtualbox and just install from conda.

Well, I tried and I got it.
First of all, I installed  Ubuntu Terminal for Windows:
https://www.microsoft.com/en-us/p/ubuntu/9nblggh4msv6?activetab=pivot:overviewtab

Then the initialization should be performed: 
https://docs.microsoft.com/en-us/windows/wsl/initialize-distro

To learn about Ubuntu Terminal (hot keys and etc.) you can use this guide:
https://help.ubuntu.com/community/UsingTheTerminal

Now you can install python via anaconda:
https://gist.github.com/kauffmanes/5e74916617f9993bc3479f401dfec7da

After this trying to install any packeges I faced the problem: CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/anaconda/linux-64/repodata.json> Elapsed: -

Following this link there is discussion of this issue:
https://github.com/conda/conda/issues/6007

As for me the problem was solved by command:
conda config --set ssl_verify no

Then just instal cyipopt:
conda install -c conda-forge cyipopt

For convenient use of ipopt, I call Jupiter from the Ubuntu console:
jupyter notebook

**Comment by moorepants** [comment]
Great. that is a useful work around to using this on Windows!

**Comment by moorepants** [comment]
We have updated the setup.py to work with windows in #49 and instructions are added in #50. Please reopen if you still can't get it installed on Windows.
