### ISSUE TITLE
pip3 install?

### ISSUE THREAD

**Issue by edwardsun** [matthias-k/cyipopt#60]
Hi,

Is there a way to install the package using pip3?
Ideally and hopefully a user only needs to use "pip3 install" and does not need to worry about compilations, etc
Thanks.

**Comment by moorepants** [comment]
This requires the someone to build wheels for various platforms. See issue #41.

If you'd like to contribute a build process for the wheels, we'd happily accept it. It would be nice if they built on the CI services. I suspect that they could be built to dynamically link with an installed IPOPT.

Otherwise, we recommend using conda for binary based installs.

I'm closing this in favor of the issue #41. Feel free to reopen if I misinterpreted.
